### ISSUE TITLE
Missing s in table name

### ISSUE THREAD

**Issue by rsd** [ksindi/flask-sqlacodegen#10]
Hello,

For some reason sqlacodegen (1.1.6), misses the s in the table name.
I have the following tables in mysql (5.6.28):
podcast -> Podcast
podcast_item -> PodcastItem
podcast_items -> PodcastItem   <-- Missing the "s"

I believe that this should be something trivial to spot in the table name translation code.

Let me know if I can help in any way.

**Comment by ksindi** [comment]
@rsd Sorry for the late response. I think you're right: class names are made singular. You would have to modify: https://github.com/ksindi/flask-sqlacodegen/blob/master/sqlacodegen/codegen.py#L339. Feel free to create a pull request.
