### ISSUE TITLE
--noclasses is ignored.

### ISSUE THREAD

**Issue by ByteJuggler** [ksindi/flask-sqlacodegen#15]
It seems that the --noclasses switch is not implemented.  Although it is recognized, the argument value isn't passed to CodeGenerator() or otherwise referenced anywhere that I can see.

**Comment by ByteJuggler** [comment]
This [patch](https://gist.github.com/ByteJuggler/362aec28dcea4756f43927c69c663026) fixes it.  In addition I added the 'if __name__ == "__main__": ...' to main module to allow for running from command line and from IDE without requiring package installation.

**Comment by ByteJuggler** [comment]
This [patch](https://gist.github.com/ByteJuggler/362aec28dcea4756f43927c69c663026) fixes it.  In addition I added the 'if __name__ == "__main__": ...' to main module to allow for running from command line and from IDE without requiring package installation.

**Comment by ksindi** [comment]
@ByteJuggler thanks for the patch! I added it to master and released a new version (v1.1.6.1) with the fix.
